---

version: 2

jobs:
  test:
    docker:
      - image: circleci/ruby:2.4
    working_directory: ~/repo
    steps:
      - checkout
      - run: bundle exec rake db:create db:migrate
      - run: bundle exec rake assets:precompile
      - run: bundle install
      - run: bundle exec rspec

  lint:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: bundle install
      - run: ./script/install_linters.sh
      - run: ./script/check_static.rb

workflows:
  version: 2
  test-and-lint:
    jobs:
      - test
      - lint
